"""Goal 5 local operations, audit ledger, automation, and API."""

from stock_ai.operations.api import create_app
from stock_ai.operations.automation import (
    DAILY_STAGES,
    AutomationBlockedError,
    AutomationContext,
    DailyAutomation,
    StageResult,
    windows_task_scheduler_script,
)
from stock_ai.operations.fixture import bootstrap_goal5_fixture
from stock_ai.operations.models import (
    AutomationJobRecord,
    AutomationStage,
    CashDifference,
    DailyOperationStatus,
    DecisionPolicySnapshot,
    DecisionReview,
    ExecutionImportPreview,
    ImportConflict,
    ImportStatus,
    JobStatus,
    ModelDriftStatus,
    NotificationChannel,
    NotificationRecord,
    NotificationStatus,
    PaperCalendarSnapshot,
    PaperOutcome,
    PaperReadout,
    PaperReadoutPeriod,
    PaperSeriesPoint,
    PaperSummary,
    PipelineState,
    PositionDifference,
    PositionReconciliationPreview,
    RankingRecord,
)
from stock_ai.operations.store import (
    OperationalConflictError,
    OperationalIntegrityError,
    OperationalStore,
)

__all__ = [
    "DAILY_STAGES",
    "AutomationBlockedError",
    "AutomationContext",
    "AutomationJobRecord",
    "AutomationStage",
    "CashDifference",
    "DailyAutomation",
    "DailyOperationStatus",
    "DecisionPolicySnapshot",
    "DecisionReview",
    "ExecutionImportPreview",
    "ImportConflict",
    "ImportStatus",
    "JobStatus",
    "ModelDriftStatus",
    "NotificationChannel",
    "NotificationRecord",
    "NotificationStatus",
    "OperationalConflictError",
    "OperationalIntegrityError",
    "OperationalStore",
    "PaperCalendarSnapshot",
    "PaperOutcome",
    "PaperReadout",
    "PaperReadoutPeriod",
    "PaperSeriesPoint",
    "PaperSummary",
    "PipelineState",
    "PositionDifference",
    "PositionReconciliationPreview",
    "RankingRecord",
    "StageResult",
    "bootstrap_goal5_fixture",
    "create_app",
    "windows_task_scheduler_script",
]
